const { test, expect } = require("@playwright/test");

test("deal evidence, money, operations, and reconciliation work through the browser", async ({ page, request }, testInfo) => {
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  const before = await (await request.get("/api/state")).json();
  await page.goto("/");
  await expect(page.locator("#connection")).toHaveText("Saved locally");
  const address = "123 Browser " + testInfo.project.name + " St";
  const property = page.locator("#property-form");
  await property.locator('[name="address"]').fill(address);
  await property.locator('[name="city"]').fill("Fort Wayne");
  await property.locator('[name="state"]').fill("IN");
  await property.locator('[name="zip"]').fill("46802");
  await property.getByRole("button", { name: "Save property" }).click();
  await expect(page.locator("#property-title")).toHaveText(address);
  await expect(page.locator("#count-properties")).toHaveText(String(before.properties.length + 1));

  const fact = page.locator("#fact-form");
  await fact.locator('[name="attribute"]').fill("sqft");
  await fact.locator('[name="value"]').fill("1800");
  await fact.locator('[name="provider"]').fill("County assessor");
  await fact.locator('[name="url"]').fill("https://example.com/parcel");
  await fact.getByRole("button", { name: "Record fact" }).click();
  await expect(page.locator("#facts")).toContainText("sqft: 1800");
  await expect(page.locator("#facts a")).toHaveAttribute("href", "https://example.com/parcel");

  // User-provided values must appear as text rather than execute HTML.
  await fact.locator('[name="attribute"]').fill("note");
  await fact.locator('[name="value_format"]').selectOption("text");
  await fact.locator('[name="value"]').fill('<img src=x onerror="window.injected=true">');
  await fact.locator('[name="provider"]').fill("Inspection");
  await fact.getByRole("button", { name: "Record fact" }).click();
  await expect(page.locator("#facts")).toContainText('<img src=x onerror="window.injected=true">');
  expect(await page.evaluate(() => window.injected)).toBeUndefined();
  expect(await page.locator("#facts img").count()).toBe(0);

  const prediction = page.locator("#prediction-form");
  await prediction.locator('[name="predicted_value"]').fill("30000");
  await prediction.getByRole("button", { name: "Save estimate" }).click();
  await expect(page.locator("#predictions")).toContainText("Estimated $30,000.00");
  const outcome = page.locator(".outcome-form");
  await outcome.locator('[name="actual_value"]').fill("33000");
  await outcome.locator('[name="provider"]').fill("Contractor invoice");
  await outcome.getByRole("button", { name: "Record outcome" }).click();
  await expect(page.locator("#predictions")).toContainText("Actual $33,000.00");
  await expect(page.locator("#learning")).toContainText("predicted=30000");
  await expect(page.locator(".outcome-form")).toHaveCount(0);

  const dealStart = page.locator("#deal-form");
  await dealStart.locator('[name="strategy"]').selectOption("assignment");
  await dealStart.getByRole("button", { name: "Start deal" }).click();
  const underwriting = page.locator(".underwrite-form");
  const assumptions = {property_type:"single_family",expected_exit_price:"240000",buyer_repairs:"30000",buyer_funding_holding:"8000",buyer_closing:"5000",buyer_selling_costs:"10000",buyer_minimum_profit:"42000",target_assignment_fee:"20000",owner_transaction_costs:"4000",partner_payout_allowance:"2000",contingency:"2000",desired_owner_net:"10000"};
  for (const [name,value] of Object.entries(assumptions)) await underwriting.locator('[name="'+name+'"]').fill(value);
  await underwriting.locator('[name="basis"]').fill("Browser test assumptions; not a live valuation.");
  await underwriting.getByRole("button", { name: "Save underwriting scenarios" }).click();
  await expect(page.locator("#deal-board")).toContainText("Owner max contract:");
  await expect(page.locator("#deal-board")).toContainText("Manual scenario analysis");
  const buyer = page.locator("#buyer-form");
  await buyer.locator('[name="name"]').fill("Browser Buyer");
  await buyer.locator('[name="locations"]').fill("Fort Wayne, IN");
  await buyer.locator('[name="max_total_price"]').fill("200000");
  await buyer.locator('[name="max_repairs"]').fill("50000");
  await buyer.getByRole("button", { name: "Save buyer" }).click();
  await expect(page.locator("#buyer-results")).toContainText("Browser Buyer");
  await page.getByRole("button", { name: "Run buyer matching" }).click();
  await expect(page.locator("#deal-board")).toContainText("Browser Buyer");
  await expect(page.locator("#deal-board")).toContainText("Funding evidence needs current owner review");

  const plan = page.locator(".money-plan-form");
  for (const [name,value] of Object.entries({seller_price:"125000",assignment_fee:"20000",planned_cash_at_risk:"6000",max_cash_at_risk:"10000"})) await plan.locator('[name="'+name+'"]').fill(value);
  await plan.locator('[name="basis"]').fill("Synthetic owner terms, funds and expenses");
  await plan.getByRole("button", { name: "Save proposed terms" }).click();
  await expect(page.locator(".fixed-forecasts")).toContainText("Net contribution: $12,000.00");
  const ledger = page.locator(".ledger-form");
  await ledger.locator('[name="category"]').selectOption("transaction");
  await ledger.locator('[name="amount"]').fill("4000");
  await ledger.locator('[name="evidence_reference"]').fill("synthetic-bank-payment");
  await ledger.locator('[name="note"]').fill("Synthetic transaction cost actually paid");
  await ledger.getByRole("button", { name: "Record cash movement" }).click();
  await expect(page.locator(".finance-risk")).toContainText("Cash at risk now: $4,000.00");
  const task = page.locator(".task-form");
  await task.locator("..").locator("summary").click();
  await task.locator('[name="title"]').fill("Synthetic title hold");
  await task.locator('[name="expected_result"]').fill("Owner reviewed evidence");
  await task.locator('[name="operation"]').selectOption("13");
  await task.locator('[name="kind"]').selectOption("exception");
  await task.locator('[name="blocking_stage"]').selectOption("any");
  await task.getByRole("button", { name: "Save operation task" }).click();
  const exception = page.locator(".operation-tasks .evidence-row").filter({hasText:"Synthetic title hold"});
  await exception.getByText("Record completion", {exact:true}).click();
  await exception.locator('.task-resolution-form [name="note"]').fill("Resolved using synthetic evidence");
  await exception.locator('.task-resolution-form [name="evidence_reference"]').fill("synthetic-title-review");
  await exception.getByRole("button", {name:"Complete task",exact:true}).click();
  await expect(exception.locator(".pill")).toHaveText("done");
  const stage = page.locator("#deal-board > .inline-form");
  await stage.locator('[name="stage"]').selectOption("lost");
  await stage.locator('[name="note"]').fill("Synthetic seller chose another solution");
  await stage.getByRole("button", {name:"Save stage"}).click();
  const recon = page.locator(".reconciliation-form");
  await recon.locator('[name="note"]').fill("All costs entered; synthetic failed deal");
  await recon.locator('[name="evidence_reference"]').fill("synthetic-complete-costs");
  await recon.locator('input[type="checkbox"]').check();
  await recon.getByRole("button", {name:"Reconcile deal"}).click();
  await expect(page.locator(".reconciliation-status")).toContainText("Reconciled · actual -$4,000.00");
  await expect(page.locator("#money-scorecard")).toContainText("Reconciled contribution");

  const lookup = page.locator(".parcel-research-form");
  await lookup.locator('[name="parcel_key"]').fill("029999999999999999");
  await lookup.getByRole("button", {name:"Look up official record"}).click();
  await expect(page.locator(".research-snapshot")).toContainText("SYNTHETIC TEST OWNER");
  const review=page.locator(".research-review-form");
  await review.locator('[name="note"]').fill("Synthetic identity review for browser fixture");
  await review.locator('[name="mismatch_explanation"]').fill("Synthetic test adapter has an intentionally different example address");
  await review.locator('input[type="checkbox"]').check();
  await review.getByRole("button",{name:"Save source review"}).click();
  await expect(page.locator(".research-snapshot")).toContainText("sourced facts accepted");
  await expect(page.locator("#facts")).toContainText("recorded owner name: SYNTHETIC TEST OWNER");

  await page.reload();
  await expect(page.locator("#property-title")).toHaveText(address);
  await expect(page.locator("#facts")).toContainText("sqft: 1800");
  await expect(page.locator("#learning")).toContainText("actual=33000");
  await page.locator("#search").fill("no-matching-address");
  await expect(page.locator("#property-list")).toContainText("No matching properties.");
  await page.locator("#search").fill("");
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  expect(errors).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("workspace.png"), fullPage: true });
});
