const { test, expect } = require("@playwright/test");

test("seller evidence, current reply review, stop control and synthetic practice", async ({ page }, testInfo) => {
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  const suffix = testInfo.project.name + "-" + Date.now();
  await page.goto("/");
  const property = page.locator("#property-form");
  await property.locator("[name=address]").fill("123 Synthetic Conversation " + suffix);
  await property.locator("[name=city]").fill("Fort Wayne");
  await property.locator("[name=state]").fill("IN");
  await property.getByRole("button", { name: "Save property" }).click();
  await expect(page.locator("#property-title")).toHaveText("123 Synthetic Conversation " + suffix);
  const workspace = page.locator("#seller-workspace");
  const contact = workspace.locator(".contact-form");
  await contact.locator("[name=name]").fill("SYNTHETIC SELLER " + suffix);
  await contact.locator("[name=email]").fill(suffix + "@example.test");
  await contact.getByRole("button", { name: "Save contact" }).click();
  await expect(workspace.getByRole("heading", { name: "SYNTHETIC SELLER " + suffix })).toBeVisible();
  await workspace.getByText("Contact permission & suppression", { exact: true }).click();
  const permission = workspace.locator(".permission-form");
  await permission.locator("[name=status]").selectOption("permitted");
  await permission.locator("[name=note]").fill("Synthetic contact asked for this conversation.");
  await permission.locator("[name=evidence_reference]").fill("synthetic-permission");
  await permission.getByRole("button", { name: "Save permission record" }).click();
  await expect(page.locator("#message")).toHaveText("Permission record saved.");
  const priorities = workspace.locator(".seller-profile-form");
  await priorities.locator("[name=status]").selectOption("confirmed");
  await priorities.locator("[name=goal]").fill("SYNTHETIC: Understand a possible sale.");
  await priorities.locator("[name=timing]").fill("Flexible; no deadline stated.");
  await priorities.locator("[name=pain_points][value=price]").check();
  await priorities.locator("[name=evidence_reference]").fill("synthetic-discovery");
  await priorities.getByRole("button", { name: "Save seller priorities" }).click();
  await expect(page.locator("#message")).toHaveText("Seller priorities saved.");
  const conversation = workspace.locator(".conversation-form");
  await conversation.locator("[name=category]").selectOption("price");
  await conversation.locator("[name=body]").fill("SYNTHETIC: The amount matters to me. What can you explain?");
  await conversation.locator("[name=evidence_reference]").fill("synthetic-thread:1");
  await conversation.getByRole("button", { name: "Save conversation" }).click();
  await expect(page.locator("#message")).toHaveText("Conversation saved.");
  await workspace.getByRole("button", { name: "Suggest a reply from saved conversation" }).click();
  const review = workspace.locator(".reply-review-form");
  await expect(review.locator("[name=final_body]")).toHaveValue(/price is a concern/);
  await review.locator("[name=note]").fill("Synthetic reply asks rather than guesses; makes no terms or funding promise.");
  await review.locator("[name=owner_reviewed]").check();
  await review.getByRole("button", { name: "Save reviewed draft" }).click();
  await expect(workspace.getByText("reviewed · current context", { exact: true })).toBeVisible();
  await workspace.screenshot({ path: testInfo.outputPath("seller-reply.png") });
  await workspace.getByText("Record a conversation", { exact: true }).click();
  const stop = workspace.locator(".conversation-form");
  await stop.locator("[name=body]").fill("Please stop contacting me.");
  await stop.locator("[name=evidence_reference]").fill("synthetic-thread:stop");
  await stop.getByRole("button", { name: "Save conversation" }).click();
  await expect(workspace.getByText("Permission: suppressed", { exact: true })).toBeVisible();
  await expect(workspace.getByRole("button", { name: "Suggest a reply from saved conversation" })).toBeDisabled();
  await workspace.getByText("Reply drafts · 1", { exact: true }).click();
  await expect(workspace.getByText("void · changed context", { exact: true })).toBeVisible();
  await page.locator("#sales-training > summary").click();
  const training = page.locator("#training-workspace");
  await training.locator("select[name=scenario_id]").selectOption("stop");
  await expect(training.getByText("SYNTHETIC: Stop contacting me and remove me from your list.", { exact: true })).toBeVisible();
  const practice = training.locator(".practice-form");
  await practice.locator("[name=response]").fill("Understood. I will stop contacting you and record the request.");
  for (const name of ["listening", "grounding", "clarity", "next_step", "economics", "respect"]) await practice.locator("[name="+name+"]").selectOption("2");
  await practice.locator("[name=review_note]").fill("Synthetic response acknowledges the refusal and contains no continuing solicitation.");
  await practice.getByRole("button", { name: "Save practice & self-assessment" }).click();
  await training.getByText(/Practice history ·/).click();
  await expect(training.getByText("stop · 12/12 · Practice threshold met", { exact: true }).first()).toBeVisible();
  await training.screenshot({ path: testInfo.outputPath("training.png") });
  await page.screenshot({ path: testInfo.outputPath("conversations-training.png"), fullPage: true });
  await page.reload();
  await expect(workspace.getByText("Permission: suppressed", { exact: true })).toBeVisible();
  const saved = await page.request.get("/api/state"); const state = await saved.json();
  const stored = state.communications.contacts.find(c=>c.email === suffix+"@example.test");
  expect(stored.messages).toHaveLength(2); expect(stored.profiles[0].status).toBe("confirmed");
  expect(state.training.attempts.some(a=>a.response.startsWith("Understood. I will stop"))).toBeTruthy();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
