const { test, expect } = require("@playwright/test");

test("explicit source update, partial failure, owner publication, withdrawal and restore", async ({ page }, testInfo) => {
  const errors=[];page.on("pageerror",error=>errors.push(error.message));
  const suffix=testInfo.project.name+"-"+Date.now();
  const before=await(await page.request.get("/api/state")).json();
  await page.goto("/");await expect(page.locator("#connection")).toHaveText("Saved locally");
  // Viewing the app must not start external research or a new update run.
  const opened=await(await page.request.get("/api/state")).json();
  expect(opened.knowledge.runs.length).toBe(before.knowledge.runs.length);
  await page.locator("#knowledge-research > summary").click();
  const box=page.locator("#knowledge-workspace");const update=box.locator(".knowledge-update-form");
  for(const checkbox of await update.locator("[name=source_ids]").all())await checkbox.uncheck();
  await update.locator("[name=source_ids][value=seller_research]").check();
  await update.locator("[name=source_ids][value=email_rules]").check();
  await update.locator("[name=jurisdiction]").fill("SYNTHETIC browser scope "+suffix);
  await update.getByRole("button",{name:"Update Knowledge",exact:true}).click();
  await expect(page.locator("#message")).toHaveText("Knowledge check started. Results require review.");
  const after=await(await page.request.get("/api/state")).json();
  expect(after.knowledge.runs.length).toBe(before.knowledge.runs.length+1);
  const run=after.knowledge.runs.find(r=>r.jurisdiction==="SYNTHETIC browser scope "+suffix);
  expect(run.status).toBe("partially_complete");
  const source=run.snapshots.find(s=>s.source_id==="seller_research");
  const failed=run.snapshots.find(s=>s.source_id==="email_rules");
  expect(failed.status).toBe("failed");expect(failed.checked_at).toBeNull();
  const card=box.locator('[data-snapshot-id="'+source.id+'"]');
  await expect(card).toContainText("SYNTHETIC");
  await card.getByText("Review source and write an internal knowledge note",{exact:true}).click();
  const review=card.locator(".knowledge-review-form");
  await review.locator("[name=title]").fill("Synthetic reviewed insight "+suffix);
  await review.locator("[name=claim]").fill("SYNTHETIC interpretation for testing: ask about actual priorities instead of guessing.");
  await review.locator("[name=applicability]").fill("Synthetic practice only. No law, market price, consent or transaction authority verified.");
  await review.locator("[name=review_reference]").fill("synthetic-source-review");
  await review.locator("[name=note]").fill("Original fixture wording and context compared.");
  await review.locator("[name=owner_verified_source]").check();
  await review.getByRole("button",{name:"Publish reviewed note"}).click();
  await expect(page.locator("#message")).toHaveText("Reviewed internal knowledge published. Execution rules unchanged.");
  const published=await(await page.request.get("/api/state")).json();
  const item=published.knowledge.items.find(i=>i.title==="Synthetic reviewed insight "+suffix);
  expect(item.status).toBe("active");expect(item.execution_policy_changed).toBe(false);
  const active=box.locator('[data-item-id="'+item.id+'"]');
  await expect(active.getByRole("heading",{name:item.title,exact:true})).toBeVisible();
  await active.getByText("Withdraw this version",{exact:true}).click();
  const withdraw=active.locator(".knowledge-version-form");
  await withdraw.locator("[name=note]").fill("Synthetic withdrawal test.");
  await withdraw.locator("[name=evidence_reference]").fill("synthetic-version-review");
  await withdraw.locator("[name=owner_reviewed]").check();
  await withdraw.getByRole("button",{name:"Withdraw version"}).click();
  await expect(page.locator("#message")).toHaveText("Knowledge version updated with an audit record.");
  await box.getByText(/Knowledge versions & rollback ·/).click();
  const historical=box.locator('[data-item-id="'+item.id+'"]');
  await historical.getByText("Restore this historical version",{exact:true}).click();
  const restore=historical.locator(".knowledge-version-form");
  await restore.locator("[name=note]").fill("Synthetic restore reviewed.");
  await restore.locator("[name=evidence_reference]").fill("synthetic-version-review:restore");
  await restore.locator("[name=owner_reviewed]").check();
  await restore.getByRole("button",{name:"Restore version"}).click();
  await expect(box.locator('[data-item-id="'+item.id+'"]')).toContainText("active");
  await box.screenshot({path:testInfo.outputPath("knowledge-review.png")});
  await page.reload();await page.locator("#knowledge-research > summary").click();
  await expect(box.getByRole("heading",{name:item.title,exact:true})).toBeVisible();
  const final=await(await page.request.get("/api/state")).json();
  expect(final.knowledge.items.find(i=>i.id===item.id).status).toBe("active");
  expect(final.knowledge.events.some(e=>e.item_id===item.id&&e.action==="activate")).toBeTruthy();
  expect(final.knowledge.runs.length).toBe(before.knowledge.runs.length+1);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
