const {test,expect} = require("@playwright/test");

test("property-independent relationship, reply schedule and stop request",async({page,request},testInfo)=>{
  const unique=`${Date.now()}-${Math.random()}`;
  const errors=[];page.on("pageerror",error=>errors.push(error.message));
  await page.goto("/relationships");
  await page.getByText("Add a relationship",{exact:true}).click();
  const form=page.locator("#relationship-create-form form");
  await form.getByLabel("Name",{exact:true}).fill(`<img src=x onerror=alert(1)> ${unique}`);
  await form.getByLabel("Email",{exact:true}).fill(`synthetic-${unique}@example.test`);
  await form.getByLabel("Areas of interest (one per line)",{exact:true}).fill("Fort Wayne, IN");
  await form.getByLabel("Relationship source / evidence reference",{exact:true}).fill("Synthetic introduction only");
  await form.locator('[name="permission"]').selectOption("owner_reviewed");
  await form.getByLabel("Permission review reference",{exact:true}).fill("Synthetic permission only");
  const before=await (await request.get("/api/relationships")).json();
  await form.getByLabel("Next follow-up date",{exact:true}).fill(before.today);
  await form.getByLabel("Next action",{exact:true}).fill("Ask about current areas and timing");
  await form.getByRole("button",{name:"Save relationship",exact:true}).click();
  await expect(page.locator("#relationship-message")).toContainText("No message was sent");
  const after=await (await request.get("/api/relationships")).json();
  const record=after.relationships.find(r=>r.profile.email===`synthetic-${unique}@example.test`);
  expect(record).toBeTruthy();
  const card=page.locator(`[data-relationship-id="${record.id}"]`);
  await expect(card).toContainText("Follow-up due today");
  await expect(card.locator("img")).toHaveCount(0);
  await page.reload();await expect(card).toContainText("1 profile versions");
  await page.locator("#relationship-create").evaluate(node=>node.open=false);
  await page.screenshot({path:testInfo.outputPath("relationship-desk.png"),fullPage:true});
  await card.getByText("Record conversation / next step",{exact:true}).click();
  const eventForm=card.locator("form").first();
  await eventForm.locator('[name="direction"]').selectOption("incoming");
  await eventForm.getByLabel("Conversation evidence reference",{exact:true}).fill("Synthetic reply only");
  await eventForm.getByLabel("What happened / actual conversation",{exact:true}).fill("We buy nearby. Please send your criteria questions.");
  await eventForm.getByRole("button",{name:"Record interaction",exact:true}).click();
  await expect(card).toContainText("Next step not scheduled");
  await page.locator("#relationship-filter").selectOption("due");await expect(card).toBeHidden();
  await page.locator("#relationship-filter").selectOption("all");
  await card.getByText("Record conversation / next step",{exact:true}).click();
  await eventForm.locator('[name="direction"]').selectOption("incoming");
  await eventForm.getByLabel("Conversation evidence reference",{exact:true}).fill("Synthetic stop request only");
  await eventForm.getByLabel("What happened / actual conversation",{exact:true}).fill("Please stop emailing me.");
  await eventForm.getByRole("button",{name:"Record interaction",exact:true}).click();
  await expect(card).toContainText("Do not contact — recorded suppression");
  await expect(card.getByText("Message text for owner review",{exact:true})).toHaveCount(0);
  await page.locator("#relationship-filter").selectOption("blocked");await expect(card).toBeVisible();
  await card.screenshot({path:testInfo.outputPath("relationship-card.png")});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
