const { test, expect } = require('@playwright/test');
test('one button gives usable property cards without entering numbers or addresses',async({page})=>{
  const id='AssessorParcel.dbo.ParcelInfo.UnformattedStateKey',address='AssessorParcel.dbo.ParcelInfo.LocationAddress',value='AssessorParcel.dbo.ParcelInfo.TotalAV';
  const source={id:'allen_comparable_parcels',name:'County sample',activated_at:'test-activation'};
  await page.route('**/api/sentras/meta?*',r=>r.fulfill({json:{active_registry:[source],candidates:[],summary:{active:1,quarantined:0,proposed:0},provider_readiness:{data_gov:'configured'}}}));
  await page.route('**/api/sentras/evidence',r=>r.fulfill({json:{profiles:[{sentra_id:source.id,activation:source.activated_at,version:'v1',cost_cents:0,identity_field:id,field_map:{parcel_identity:[id],assessment:[value]}}],runs:[]}}));
  let acquisitions=0;
  await page.route('**/api/sentras/meta/execute',r=>{
    acquisitions++;expect(r.request().postDataJSON()).toEqual({sentra_id:source.id});
    return r.fulfill({json:{source_url:'https://example.gov/MapServer/0',payload:{features:Array.from({length:5},(_,i)=>({attributes:{[id]:`P-${i}`,[address]:`${100+i} MAIN ST`,[value]:150000}}))}}});
  });
  await page.goto('/sentras');
  await expect(page.getByLabel('Parcel or record identity')).not.toBeVisible();
  await page.getByRole('button',{name:'Find properties to review',exact:true}).click();
  await expect(page.locator('#quick-results article')).toHaveCount(3);
  await expect(page.locator('#quick-results')).toContainText('100 MAIN ST');
  await expect(page.locator('#quick-results')).toContainText('$150,000');
  await expect(page.locator('#quick-note')).toContainText('not ranked by profit');
  await expect(page.getByRole('link',{name:'Open official county record'})).toHaveCount(3);
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedBrief=text;}}}));
  await page.getByRole('button',{name:'Copy research summary'}).first().click();
  await expect(page.getByRole('button',{name:'Summary copied'})).toBeVisible();
  expect(await page.evaluate(()=>window.copiedBrief)).toContain('100 MAIN ST');
  await page.getByRole('button',{name:'Show 3 more properties',exact:true}).click();
  await expect(page.locator('#quick-results article')).toHaveCount(2);
  await expect(page.locator('#quick-results')).toContainText('103 MAIN ST');
  expect(acquisitions).toBe(1);
  const d=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));
  expect(d.content).toBeLessThanOrEqual(d.width+1);
});

test('one-click never acquires an unavailable county source',async({page})=>{
  let acquisitions=0;
  await page.route('**/api/sentras/meta/execute',r=>{acquisitions++;return r.fulfill({json:{}});});
  await page.route('**/api/sentras/meta?*',r=>r.fulfill({json:{active_registry:[],candidates:[],summary:{active:0,quarantined:0,proposed:0},provider_readiness:{data_gov:'configured'}}}));
  await page.goto('/sentras');
  await page.getByRole('button',{name:'Find properties to review',exact:true}).click();
  await expect(page.locator('#status')).toContainText('No paid search or unapproved source');
  await expect(page.locator('#quick-results article')).toHaveCount(0);
  expect(acquisitions).toBe(0);
});
test('one-click rejects a paid profile before acquiring records',async({page})=>{
  const id='AssessorParcel.dbo.ParcelInfo.UnformattedStateKey',value='AssessorParcel.dbo.ParcelInfo.TotalAV';
  const source={id:'allen_comparable_parcels',name:'County sample',activated_at:'test-activation'};
  await page.route('**/api/sentras/meta?*',r=>r.fulfill({json:{active_registry:[source],candidates:[],summary:{active:1,quarantined:0,proposed:0},provider_readiness:{data_gov:'configured'}}}));
  await page.route('**/api/sentras/evidence',r=>r.fulfill({json:{profiles:[{sentra_id:source.id,activation:source.activated_at,version:'v1',cost_cents:1,identity_field:id,field_map:{parcel_identity:[id],assessment:[value]}}],runs:[]}}));
  let acquisitions=0;
  await page.route('**/api/sentras/meta/execute',r=>{acquisitions++;return r.fulfill({json:{}});});
  await page.goto('/sentras');
  await page.getByRole('button',{name:'Find properties to review',exact:true}).click();
  await expect(page.locator('#status')).toContainText('No paid search or unapproved source');
  expect(acquisitions).toBe(0);
});
test('evidence planning and collection show unavailable coverage without inventing records', async ({page}) => {
  await page.goto('/sentras');
  await page.locator('#advanced-tools > summary').click();
  await expect(page.getByRole('heading', {name:'Evidence Compiler'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Temporal Intelligence Engine'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Shadow Intelligence Network'})).toBeVisible();
  await page.getByLabel('Parcel or record identity').fill('synthetic-A1');
  await page.getByLabel('County and state').fill('Synthetic County');
  await page.getByLabel('Evidence goals (comma separated)').fill('parcel_identity');
  await page.getByRole('button', {name:'Preview evidence plan'}).click();
  await expect(page.locator('#plan')).toContainText('"satisfiable": false');
  await page.getByRole('button', {name:'Collect evidence', exact:true}).click();
  await expect(page.locator('#status')).toContainText('Evidence run: incomplete');
  await expect(page.locator('#runs')).toContainText('synthetic-A1');
  await page.reload();
  await expect(page.locator('#runs')).toContainText('synthetic-A1');
});

test('reviewed compiler, temporal policy and shadow trial work through the operator workspace', async ({page}) => {
  await page.goto('/sentras');
  await page.locator('#advanced-tools > summary').click();
  await expect(page.locator('#sources')).toContainText('browser_baseline');
  await page.getByLabel('Parcel or record identity').fill('synthetic-A1');
  await page.getByLabel('County and state').fill('Browser Fixture County');
  await page.getByLabel('Evidence goals (comma separated)').fill('parcel_identity, assessment');
  await page.getByRole('button', {name:'Collect evidence', exact:true}).click();
  await expect(page.locator('#status')).toContainText('Evidence run: sufficient');
  await expect(page.locator('#temporal-sources')).toContainText('browser_baseline');
  await page.getByText('Review an adaptive polling policy', {exact:true}).click();
  const policy = page.locator('#temporal-policy');
  await policy.locator('[name="note"]').fill('Synthetic cadence and budget review');
  await policy.locator('[name="owner_reviewed"]').check();
  await policy.locator('[name="enabled"]').uncheck();
  await policy.getByRole('button', {name:'Save polling policy'}).click();
  await expect(page.locator('#status')).toHaveText('Adaptive polling policy saved.');
  await page.getByText('Create a shadow experiment', {exact:true}).click();
  const experiment = page.locator('#shadow-experiment');
  await experiment.locator('[name="challenger_fingerprint"]').selectOption({label:'Synthetic browser challenger'});
  await experiment.locator('[name="name"]').fill('Browser shadow comparison');
  await experiment.locator('[name="identity_field"]').fill('parcel_id');
  await experiment.locator('[name="field_map"]').fill('parcel_identity: parcel_id\nassessment: assessment');
  await experiment.locator('[name="note"]').fill('Synthetic shadow access and mapping review');
  await experiment.locator('[name="owner_reviewed"]').check();
  await experiment.getByRole('button', {name:'Create isolated experiment'}).click();
  await expect(page.locator('#status')).toHaveText('Shadow experiment created.');
  const trial = page.locator('#shadow-trial');
  await trial.locator('[name="subjects"]').fill('synthetic-A1');
  await trial.getByRole('button', {name:'Run shadow comparison'}).click();
  await expect(page.locator('#status')).toHaveText('Shadow trial: completed');
  await expect(page.locator('#shadow-reports')).toContainText('needs_outcome_review');
  const dimensions = await page.evaluate(() => ({width: window.innerWidth, content: document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width + 1);
});
