const { test, expect } = require('@playwright/test');
test('address-first research hides jargon and enables clear daily watches',async({page})=>{
  let watched=false;
  await page.route('**/api/sentras/property/watches',route=>route.fulfill({json:{watches:watched?[{id:'test-watch',address:'123 MAIN ST',enabled:true,next_due:1791500000,result:{status:'sufficient',message:'County evidence collected.',assessed_value:150000,note:'Tax assessment, not market value.'}}]:[]}}));
  await page.route('**/api/sentras/property/search',route=>route.fulfill({json:{matches:[{subject:'P-1',address:'123 MAIN ST'}],coverage_note:'Connected records only.',limited:false}}));
  await page.route('**/api/sentras/property/research',route=>{
    const data=route.request().postDataJSON();expect(data.watch).toBe(true);expect(data.threshold).toBeUndefined();watched=true;
    return route.fulfill({json:{status:'sufficient',address:'123 MAIN ST',message:'County evidence collected.',assessed_value:150000,note:'Tax assessment, not market value.',watching:true}});
  });
  await page.goto('/sentras');
  await expect(page.getByLabel('Evidence threshold')).not.toBeVisible();
  await page.getByLabel('Street address', {exact:true}).fill('123 Main');
  await page.getByRole('button',{name:'Find property',exact:true}).click();
  await page.getByRole('button',{name:'Research property',exact:true}).click();
  await expect(page.locator('#property-result')).toContainText('$150,000');
  await expect(page.locator('#property-watches')).toContainText('123 MAIN ST');
  await expect(page.getByRole('button',{name:'Stop daily updates'})).toBeVisible();
  const dimensions=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width+1);
});
test('evidence planning and collection show unavailable coverage without inventing records', async ({page}) => {
  await page.goto('/sentras');
  await page.locator('#advanced-tools > summary').click();
  await expect(page.getByRole('heading', {name:'Evidence Compiler'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Temporal Intelligence Engine'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Shadow Intelligence Network'})).toBeVisible();
  await page.getByLabel('Parcel or record identity').fill('synthetic-A1');
  await page.getByLabel('County and state').fill('Synthetic County');
  await page.getByLabel('Evidence goals (comma separated)').fill('parcel_identity');
  await page.getByRole('button', {name:'Preview evidence plan'}).click();
  await expect(page.locator('#plan')).toContainText('"satisfiable": false');
  await page.getByRole('button', {name:'Collect evidence', exact:true}).click();
  await expect(page.locator('#status')).toContainText('Evidence run: incomplete');
  await expect(page.locator('#runs')).toContainText('synthetic-A1');
  await page.reload();
  await expect(page.locator('#runs')).toContainText('synthetic-A1');
});

test('reviewed compiler, temporal policy and shadow trial work through the operator workspace', async ({page}) => {
  await page.goto('/sentras');
  await page.locator('#advanced-tools > summary').click();
  await expect(page.locator('#sources')).toContainText('browser_baseline');
  await page.getByLabel('Parcel or record identity').fill('synthetic-A1');
  await page.getByLabel('County and state').fill('Browser Fixture County');
  await page.getByLabel('Evidence goals (comma separated)').fill('parcel_identity, assessment');
  await page.getByRole('button', {name:'Collect evidence', exact:true}).click();
  await expect(page.locator('#status')).toContainText('Evidence run: sufficient');
  await expect(page.locator('#temporal-sources')).toContainText('browser_baseline');
  await page.getByText('Review an adaptive polling policy', {exact:true}).click();
  const policy = page.locator('#temporal-policy');
  await policy.locator('[name="note"]').fill('Synthetic cadence and budget review');
  await policy.locator('[name="owner_reviewed"]').check();
  await policy.locator('[name="enabled"]').uncheck();
  await policy.getByRole('button', {name:'Save polling policy'}).click();
  await expect(page.locator('#status')).toHaveText('Adaptive polling policy saved.');
  await page.getByText('Create a shadow experiment', {exact:true}).click();
  const experiment = page.locator('#shadow-experiment');
  await experiment.locator('[name="challenger_fingerprint"]').selectOption({label:'Synthetic browser challenger'});
  await experiment.locator('[name="name"]').fill('Browser shadow comparison');
  await experiment.locator('[name="identity_field"]').fill('parcel_id');
  await experiment.locator('[name="field_map"]').fill('parcel_identity: parcel_id\nassessment: assessment');
  await experiment.locator('[name="note"]').fill('Synthetic shadow access and mapping review');
  await experiment.locator('[name="owner_reviewed"]').check();
  await experiment.getByRole('button', {name:'Create isolated experiment'}).click();
  await expect(page.locator('#status')).toHaveText('Shadow experiment created.');
  const trial = page.locator('#shadow-trial');
  await trial.locator('[name="subjects"]').fill('synthetic-A1');
  await trial.getByRole('button', {name:'Run shadow comparison'}).click();
  await expect(page.locator('#status')).toHaveText('Shadow trial: completed');
  await expect(page.locator('#shadow-reports')).toContainText('needs_outcome_review');
  const dimensions = await page.evaluate(() => ({width: window.innerWidth, content: document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width + 1);
});
