const { test, expect } = require('@playwright/test');
test('daily automation saves real backend settings and survives reload and stop',async({page})=>{
  await page.goto('/sentras');
  await expect(page.locator('#automation-status')).not.toContainText('Loading');
  await page.getByRole('button',{name:'Build acquisition shortlist',exact:true}).click();
  await expect(page.locator('#brief-result')).toContainText('123 Example Rd');
  await page.getByText('Buying criteria and cost assumptions',{exact:true}).click();
  await page.getByLabel('Maximum asking price ($)').fill('123000');
  await page.getByLabel('Intended client or buyer').fill('Automation Client LLC');
  await page.getByLabel('Proposed representative company').fill('Automation Brokerage');
  await page.locator('#automation-save').click();
  await expect(page.locator('#automation-status')).toContainText('Daily updates enabled');
  const state=await (await page.request.get('/api/sentras/automation')).json();
  expect(state.policy.client_name).toBe('Automation Client LLC');
  expect(state.policy.generate_handoffs).toBe(true);
  expect(state.policy.criteria.max_price).toBe(123000);
  expect(state.external_actions).toBe(false);
  await page.reload();
  await expect(page.getByLabel('Intended client or buyer')).toHaveValue('Automation Client LLC');
  await expect(page.getByLabel('Proposed representative company')).toHaveValue('Automation Brokerage');
  await expect(page.getByLabel('Maximum asking price ($)')).toHaveValue('123000');
  await page.locator('#automation-stop').click();
  await expect(page.locator('#automation-status')).toContainText('Daily updates stopped');
  await page.reload();
  await expect(page.locator('#automation-stop')).toBeDisabled();
  const dimensions=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width+1);
});
test('representative handoff saves a draft and downloads a self-contained packet',async({page})=>{
  await page.goto('/sentras');
  await page.getByRole('button',{name:'Build acquisition shortlist',exact:true}).click();
  await expect(page.locator('#brief-result')).toContainText('123 Example Rd');
  await page.getByLabel('Intended client or buyer').fill('Browser Client LLC');
  await page.getByLabel('Proposed representative company').fill('Browser Brokerage');
  await page.getByLabel('Representative business contact (optional)').fill('office@example.test');
  await page.getByRole('button',{name:'Prepare representative handoff',exact:true}).click();
  await expect(page.locator('#handoff-result')).toContainText('Representation is not established');
  await page.locator('#handoff-result summary').click();
  await expect(page.locator('#handoff-result pre')).toContainText('$113,000.00');
  await expect(page.locator('#handoff-result pre')).toContainText('not a representation agreement');
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download handoff packet',exact:true}).click()]);
  expect(download.suggestedFilename()).toMatch(/^clubsp-handoff-.*\.txt$/);
  const fs=require('fs'); const text=fs.readFileSync(await download.path(),'utf8');
  expect(text).toContain('Browser Client LLC'); expect(text).toContain('Browser Brokerage'); expect(text).toContain('DRAFT / NOT SENT');
  await page.reload();
  await expect(page.locator('#handoff-result')).toContainText('Browser Brokerage');
  const dimensions=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width+1);
});
test('one-button acquisition brief persists real backend screening and evidence',async({page})=>{
  await page.goto('/sentras');
  await expect(page.getByLabel('Maximum asking price ($)')).not.toBeVisible();
  await page.getByRole('button',{name:'Build acquisition shortlist',exact:true}).click();
  await expect(page.locator('#brief-result')).toContainText('123 Example Rd');
  await expect(page.locator('#brief-result')).toContainText('$113,000');
  await expect(page.locator('#brief-result')).toContainText('6.84%');
  await expect(page.locator('#brief-result')).toContainText('not verified buyer demand');
  await expect(page.locator('#brief-result a').first()).toHaveAttribute('href',/\/api\/sentras\/runs\//);
  await expect(page.getByRole('button',{name:'Copy operator brief'})).toBeVisible();
  await page.reload();
  await expect(page.locator('#brief-result')).toContainText('123 Example Rd');
  await page.getByRole('button',{name:'Build acquisition shortlist',exact:true}).click();
  await expect(page.locator('#brief-status')).toContainText('no new provider requests');
  const dimensions=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width+1);
});
test('address-first research hides jargon and enables clear daily watches',async({page})=>{
  let watched=false;
  await page.route('**/api/sentras/property/watches',route=>route.fulfill({json:{watches:watched?[{id:'test-watch',address:'123 MAIN ST',enabled:true,next_due:1791500000,result:{status:'sufficient',message:'County evidence collected.',assessed_value:150000,note:'Tax assessment, not market value.'}}]:[]}}));
  await page.route('**/api/sentras/property/search',route=>route.fulfill({json:{matches:[{subject:'P-1',address:'123 MAIN ST'}],coverage_note:'Connected records only.',limited:false}}));
  await page.route('**/api/sentras/property/research',route=>{
    const data=route.request().postDataJSON();expect(data.watch).toBe(true);expect(data.threshold).toBeUndefined();watched=true;
    return route.fulfill({json:{status:'sufficient',address:'123 MAIN ST',message:'County evidence collected.',assessed_value:150000,note:'Tax assessment, not market value.',watching:true}});
  });
  await page.goto('/sentras');
  await expect(page.getByLabel('Evidence threshold')).not.toBeVisible();
  await page.getByLabel('Street address', {exact:true}).fill('123 Main');
  await page.getByRole('button',{name:'Find property',exact:true}).click();
  await page.getByRole('button',{name:'Research property',exact:true}).click();
  await expect(page.locator('#property-result')).toContainText('$150,000');
  await expect(page.locator('#property-watches')).toContainText('123 MAIN ST');
  await expect(page.getByRole('button',{name:'Stop daily updates'})).toBeVisible();
  const dimensions=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width+1);
});
test('evidence planning and collection show unavailable coverage without inventing records', async ({page}) => {
  await page.goto('/sentras');
  await page.locator('#advanced-tools > summary').click();
  await expect(page.getByRole('heading', {name:'Evidence Compiler'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Temporal Intelligence Engine'})).toBeVisible();
  await expect(page.getByRole('heading', {name:'Shadow Intelligence Network'})).toBeVisible();
  await page.getByLabel('Parcel or record identity').fill('synthetic-A1');
  await page.getByLabel('County and state').fill('Synthetic County');
  await page.getByLabel('Evidence goals (comma separated)').fill('parcel_identity');
  await page.getByRole('button', {name:'Preview evidence plan'}).click();
  await expect(page.locator('#plan')).toContainText('"satisfiable": false');
  await page.getByRole('button', {name:'Collect evidence', exact:true}).click();
  await expect(page.locator('#status')).toContainText('Evidence run: incomplete');
  await expect(page.locator('#runs')).toContainText('synthetic-A1');
  await page.reload();
  await expect(page.locator('#runs')).toContainText('synthetic-A1');
});

test('reviewed compiler, temporal policy and shadow trial work through the operator workspace', async ({page}) => {
  await page.goto('/sentras');
  await page.locator('#advanced-tools > summary').click();
  await expect(page.locator('#sources')).toContainText('browser_baseline');
  await page.getByLabel('Parcel or record identity').fill('synthetic-A1');
  await page.getByLabel('County and state').fill('Browser Fixture County');
  await page.getByLabel('Evidence goals (comma separated)').fill('parcel_identity, assessment');
  await page.getByRole('button', {name:'Collect evidence', exact:true}).click();
  await expect(page.locator('#status')).toContainText('Evidence run: sufficient');
  await expect(page.locator('#temporal-sources')).toContainText('browser_baseline');
  await page.getByText('Review an adaptive polling policy', {exact:true}).click();
  const policy = page.locator('#temporal-policy');
  await policy.locator('[name="note"]').fill('Synthetic cadence and budget review');
  await policy.locator('[name="owner_reviewed"]').check();
  await policy.locator('[name="enabled"]').uncheck();
  await policy.getByRole('button', {name:'Save polling policy'}).click();
  await expect(page.locator('#status')).toHaveText('Adaptive polling policy saved.');
  await page.getByText('Create a shadow experiment', {exact:true}).click();
  const experiment = page.locator('#shadow-experiment');
  await experiment.locator('[name="challenger_fingerprint"]').selectOption({label:'Synthetic browser challenger'});
  await experiment.locator('[name="name"]').fill('Browser shadow comparison');
  await experiment.locator('[name="identity_field"]').fill('parcel_id');
  await experiment.locator('[name="field_map"]').fill('parcel_identity: parcel_id\nassessment: assessment');
  await experiment.locator('[name="note"]').fill('Synthetic shadow access and mapping review');
  await experiment.locator('[name="owner_reviewed"]').check();
  await experiment.getByRole('button', {name:'Create isolated experiment'}).click();
  await expect(page.locator('#status')).toHaveText('Shadow experiment created.');
  const trial = page.locator('#shadow-trial');
  await trial.locator('[name="subjects"]').fill('synthetic-A1');
  await trial.getByRole('button', {name:'Run shadow comparison'}).click();
  await expect(page.locator('#status')).toHaveText('Shadow trial: completed');
  await expect(page.locator('#shadow-reports')).toContainText('needs_outcome_review');
  const dimensions = await page.evaluate(() => ({width: window.innerWidth, content: document.documentElement.scrollWidth}));
  expect(dimensions.content).toBeLessThanOrEqual(dimensions.width + 1);
});
